title: My Blog
description: A minimalist blog about Product Management and Running
author: Your Name

# Build settings
theme: minima

# Customize minima theme
minima:
  date_format: "%b %-d, %Y"

# Add navigation menu
header_pages:
  - about.md
  - product-management.md
  - running.md

# Social links
twitter_username: your_twitter_username
github_username:  your_github_username
linkedin_username: your_linkedin_username

# Show excerpts on the home page
show_excerpts: true

# Enable search
search: true