title: as above, so below
description: A blog about Product Management and Running
author: Your Name

# Build settings
theme: minima

# Use custom layout
defaults:
  -
    scope:
      path: ""
      type: "home"
    values:
      layout: "home"

# Customize minima theme
minima:
  date_format: "%b %-d, %Y"

# Header pages (uncomment and add files as needed)
# header_pages:
#   - about.md
#   - product-management.md
#   - running.md

# Remove RSS feed (optional)
# rss: false

# Add any social links you want to display
# twitter_username: your_twitter_username
# github_username:  your_github_username
# linkedin_username: your_linkedin_username